export const ERROR_CODE = {
  DB: {
    DUPLICATE_ENTRY: 'ER_DUP_ENTRY',
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    DUPLICATE_MOBILE_NUMBER: 'DUPLICATE_MOBILE_NUMBER',
    INVALID_AUTH_NUMBER: 'INVALID_AUTH_NUMBER',
  },
};
