export const RESPONSE_STATUS = {
  SUCCESS: {
    OK: 'OK',
    CREATED: 'CREATED',
  },

  REDIRECTION: {
    MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  },

  CLIENT_ERROR: {
    INVALID_ARGUMENT: 'INVALID_ARGUMENT',
    FAILED_PRECONDITION: 'FAILED_PRECONDITION',
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
  },

  SERVER_ERROR: {
    UNAVAILABLE: 'UNAVAILABLE',
    INTERNAL: 'INTERNAL',
  },
};
